### ISSUE TITLE
Chuck Norris nas páginas de deputados dos partidos - Erro 404

### ISSUE THREAD

**Issue by messivanio** [aureliano/res-publica#38]
Quando eu abro uma [página de um partido](http://res-publica.herokuapp.com/organizacional/deputados/DEM)
E eu clico em qualquer um dos botões "Detalhar".
Então eu só consigo ver uma [página de erro 404](http://res-publica.herokuapp.com/404) com a figura do Chuck Norris.

**Comment by aureliano** [comment]
Só faltou o "Dado que" pra virar uma estória de usuário. Ha! Ha! Ha!

Eu fiz uma refatoração de código pra transformar o campo _id padrão (Objectid) do mongoid na coleção partido em sigla. Como as siglas são únicas pra cada partido posso torná-las campo chave. Com isso não só consigo remover um campo da coleção como deixo de perder referência aos partidos a cada extração de dados - afinal, a cada extração, novo id (ObjectId gerado dinamicamente na inserção).

Fiz isso também com as coleções deputados e proposicaos. Dessa forma eu tenho os mesmos ganhos citados anteriormente.

Bem, limpei a base de dados e repovoei-a. Com isso o bug foi resolvido. Obrigado!
